@startuml DataObject_createObject
'https://plantuml.com/sequence-diagram

legend top left
    Project
        BI_JAVA_GCP
    Diagram
        Sequence doesExist Object
    Authors
        TESFAZGHI Robiel
        RABOT Mathieu
endlegend

actor "Client Service" as Client

participant DataObjectService
participant DataObjectConfiguration
participant SDK

Client -> DataObjectService: doesExist(objectKey)
DataObjectService -> DataObjectConfiguration: getStorage()
DataObjectConfiguration-> SDK: getStorage(credentials)
DataObjectConfiguration<- SDK: Storage
DataObjectService <- DataObjectConfiguration: Storage

alt true
    Client <- SDK: true
else
    Client <- SDK: false
end

@enduml